### PR TITLE
Some style added to the header

### PR DESCRIPTION
**Pull request by sifat009**
some little styling stuff added to the header

### CODE REVIEW

**Comment by tsl143** [comment]
@sifat009 , that's neat.
But can we have something keeping Mozilla's [new brand guidelines](https://mozilla.ninja/typography/) in mind.

**Comment by sifat009** [comment]
it would better if u provide me some demo :)

**Comment by tsl143** [comment]
I am not sure what exactly you need for demo, all the fonts are mentioned in the link,
You can put firefox addon logo in the head.
https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/addons/files/2017/03/addons-puzzle-fox-160x160.png

**Comment by tsl143** [comment]
Okay, lets put this on hold for a while, I think we need a design for this first.
Till then I will close this, you can reopen this once we have design.

**Pull request closed without merging**
